name: ece60146
channels:
  - pytorch
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - blas=1.0=mkl
  - brotlicffi=1.2.0.0=py311h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - certifi=2026.01.04=py311haa95532_0
  - cffi=2.0.0=py311h02ab6af_1
  - charset-normalizer=3.4.4=py311haa95532_0
  - expat=2.7.3=h885b0b7_4
  - filelock=3.20.0=py311haa95532_0
  - freetype=2.13.3=h0620614_0
  - giflib=5.2.2=h7edc060_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.2=py311h8598115_0
  - idna=3.11=py311haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.6=py311haa95532_0
  - jpeg=9f=ha349fce_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libdeflate=1.17=h2bbff1b_1
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libpng=1.6.54=ha15c746_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py311h827c3e9_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h827c3e9_2
  - mkl_fft=1.3.11=py311h827c3e9_0
  - mkl_random=1.2.8=py311hea22821_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py311haa95532_0
  - networkx=3.6.1=py311haa95532_0
  - numpy=2.0.1=py311hdab7c0b_1
  - numpy-base=2.0.1=py311hd01c5d8_1
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.18=h543e019_0
  - pillow=11.1.0=py311h096bfcc_0
  - pip=25.3=pyhc872135_0
  - pycparser=2.23=py311haa95532_0
  - pysocks=1.7.1=py311haa95532_1
  - python=3.11.14=h981015d_0
  - pytorch=2.5.1=py3.11_cpu_0
  - pytorch-mutex=1.0=cpu
  - pyyaml=6.0.3=py311hb9a58be_0
  - requests=2.32.5=py311haa95532_1
  - setuptools=80.9.0=py311haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - sympy=1.14.0=py311haa95532_1
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.15=hf199647_0
  - torchvision=0.20.1=py311_cpu
  - typing_extensions=4.15.0=py311haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.3=py311haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - anyio==4.12.1
      - attrs==25.4.0
      - click==8.3.1
      - colorama==0.4.6
      - datasets==4.5.0
      - dill==0.4.0
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.3.3
      - multidict==6.7.0
      - multiprocess==0.70.18
      - packaging==26.0
      - pandas==3.0.0
      - propcache==0.4.1
      - pyarrow==23.0.0
      - python-dateutil==2.9.0.post0
      - shellingham==1.5.4
      - six==1.17.0
      - tqdm==4.67.1
      - typer-slim==0.21.1
      - tzdata==2025.3
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: C:\Users\Mia Nguyen\anaconda3\envs\ece60146
